### ISSUE TITLE
cant find .h file generated by kuri_msg

### ISSUE THREAD

**Issue by gouyiyong** [kucars/kuri_mbzirc_challenge_3#10]
hi,
thanks for your amazing work, when i build in ubuntu 16.04, i found this issue and i tried to fix it but no change.

![image](https://user-images.githubusercontent.com/26245593/61696576-e4805b80-ad35-11e9-8d0e-f3bda454e24e.png)

**Comment by TarekTaha** [comment]
you have to use this package too: https://github.com/kucars/kuri_msgs

**Comment by gouyiyong** [comment]
> you have to use this package too: https://github.com/kucars/kuri_msgs

yes, i used , i just follow your command in readme.txt , i dont know why

**Comment by TarekTaha** [comment]
not sure, try to build the msgs package first independently:
`catkin_make -DCATKIN_WHITELIST_PACKAGES="kuri_msgs"` 
and check if the header files are generated inside the devel/include folder 
`cd ~/catkin_ws
`find . -name "TrackingAction.h"`

**Comment by gouyiyong** [comment]
> not sure, try to build the msgs package first independently:
> `catkin_make -DCATKIN_WHITELIST_PACKAGES="kuri_msgs"`
> and check if the header files are generated inside the devel/include folder
> `cd ~/catkin_ws `find . -name "TrackingAction.h"`
> 
> then re-compline " `catkin_make -DCATKIN_WHITELIST_PACKAGES="*"`

thanks for your patient 

> not sure, try to build the msgs package first independently:
> `catkin_make -DCATKIN_WHITELIST_PACKAGES="kuri_msgs"`
> and check if the header files are generated inside the devel/include folder
> `cd ~/catkin_ws `find . -name "TrackingAction.h"`
> 
> then re-compline " `catkin_make -DCATKIN_WHITELIST_PACKAGES="*"`

thanks for your patient reply, yes before i checked the .h file in devel/include, yes it is there, but the .cpp file cant find it. i think it is cmakelist.txt caused this issue, but i cant find anything wrong in it.
